### ISSUE TITLE
Create index?

### ISSUE THREAD

**Issue by bendangelo** [mariochavez/chroma#18]
#   collection = Chroma::Resource::Collection.get("ruby-documentation")
      #   collection.create_index

What does this do? I can't find it documented on the chroma api: https://docs.trychroma.com/reference/Client

**Comment by mariochavez** [comment]
The first line comes from `get_collection` https://docs.trychroma.com/reference/Client#get_collection
The second line seems to not be supported by the newer Chroma version.

**Comment by bendangelo** [comment]
Ok thanks. Hopefully that method can just go away in the next version.

**Comment by mariochavez** [comment]
Removed for next version.
