### ISSUE TITLE
Implement Peek?

### ISSUE THREAD

**Issue by bendangelo** [mariochavez/chroma#19]
https://docs.trychroma.com/reference/Collection#peek

This isn't on the collection. Has this already been added?

**Comment by mariochavez** [comment]
No, peek is not implemented.

**Comment by bendangelo** [comment]
Ok thanks. Are there plans to keep this gem up to date with Chromadb?

**Comment by mariochavez** [comment]
Look at latest version of Chroma, `peek` is not present in the REST API, but Python client has the method. Peek is calling `get` internally and it is passing the `limit` param.

```
Chroma.connect_host = "http://localhost:8000"
Chroma.logger = Logger.new($stdout)
Chroma.log_level = Chroma::LEVEL_DEBUG

collection = Chroma::Resources::Collection.get("my-collection")
result = collection.get(limit: 2) # This is the same as peek.
```
