### ISSUE TITLE
Delete Collection Fails

### ISSUE THREAD

**Issue by bendangelo** [mariochavez/chroma#21]
```
Chroma::InvalidRequestError:
  \n                You must provide either ids, where, or where_document to delete. If\n                you want to delete all data in a collection you can delete the\n                collection itself using the delete_collection method. Or alternatively,\n                you can get() all the relevant ids and then delete them.\n    
```
Running this: Chroma::Resources::Collection.delete chroma_collection_name`

Seems the endpoint changed.

**Comment by mariochavez** [comment]
I'm using Chroma server version 0.4.24 and `Chroma::Resources::Collection.delete(collection_name)` works fine. Looking at Python API code, `delete` method uses collection name.

If you are trying to delete collection's embeddings then, yes, you need to pass the documents Ids to delete.
