### ISSUE TITLE
Query with Filters

### ISSUE THREAD

**Issue by ausangshukla** [mariochavez/chroma#24]
I have an embedding created with metadata: {name: "XYZ", date: Date.parse("2023-03-01")}
Now Id like to query
    collection.query(query_embeddings: [embedding], results: n_results, where: {name: "XYZ"})

I always get 0 results. How should I filter by metadata, any pointers/exapmles would be helpful

**Comment by mariochavez** [comment]
`where` parameter needs to be a valid JSON document.
```
collection.query(query_embeddings: [embedding], results: n_results, where: { "name": "XYZ" })
```
