### ISSUE TITLE
Why where is mandatory param? Shouldn't it be optional as per chromadb?

### ISSUE THREAD

**Issue by vikas-0** [mariochavez/chroma#29]
ERROR -- : message=Client error response code=400 body={"error":"InvalidArgumentError","message":"Expected where to have exactly one operator, got {}"}
/usr/local/rvm/gems/default/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': InvalidArgumentError (Chroma::APIError)

**Comment by matsubo** [comment]
# My situation

I've got same error.

```ruby
>  question_embedding  = [1.8638756275177002,
 -0.023308515548706055,
 -2.544995069503784,
 1.411717176437378,
 1.2810852527618408,
 1.5934257507324219,
 0.3053443729877472,
 -1.9993882179260254,
 0.11245744675397873,
 -0.8461968302726746,
 -2.4017527103424072,
 -1.3157418966293335,
 -4.111044406890869,
 -0.6862623691558838,
 0.6185646653175354,
 -1.1491460800170898]
> collection = Chroma::Resources::Collection.get(collection_name)
> collection.query(query_embeddings: question_embedding)
```

Then I got following error from the 
```
E, [2024-11-13T23:36:07.016314 #154] ERROR -- : message=Client error response code=400 body={"error":"InvalidArgumentError","message":"Expected where to have exactly one operator, got {}"}
(my-rag):115:in `<main>': InvalidArgumentError (Chroma::APIError)
```

Server version
```
> Chroma::Resources::Database.version
=> "0.5.18"
```

I've also tried following option according to the option shown in [the python library](https://docs.trychroma.com/guides#querying-a-collection) but the errror message does not change.

```ruby
     collection.query(
        query_embeddings: [ question_embedding ],
        where: {"metadata_field": "is_equal_to_this"}
      )
```


# Temporary solution

I specified `where` and `where_document` key with nil then the server responses success.

```ruby
collection = Chroma::Resources::Collection.get(collection_name)
collection.query(
  query_embeddings: question_embedding,
  where: nil,
  where_document: nil
)

```

The ChromaDB server does not allow empty array or hash.

**Comment by justi** [comment]
I've got the same error.

@matsubo thanks for workaround.

**Comment by mariochavez** [comment]
Chroma API changed at some point that made invalid to send empty Hashes for `where` and `where_documents`.

**Comment by mariochavez** [comment]
New release was pushed to Ruby gems v0.8.2
